# Introduction
This file will be used for defvelopment of reshape_maps() function.
The function reshape_maps() will be used to reorganize Belief+Affinity maps genrated by ResPose.
In the final stage the function will also work with different number of classes.

In [1]:
import numpy as np

batch = 16
W, H = 10,10
numb_maps = 25
numBeliefMap = 9
numAffinity = 16
out = np.arange(batch * numb_maps * W * H)

print("Before Resizing shape of out:")
print(out.shape)
out = out.reshape(batch, numb_maps, W, H)
print("After Resizing shape of out:")
print(out.shape)

InputList = [out, out, out, out, out, out]

Before Resizing shape of out:
(40000,)
After Resizing shape of out:
(16, 25, 10, 10)


In [2]:
out[0,0,:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [3]:
"""
Input: 
Will be 6 of this "out" array
e.g:
[out1, out2, out3, out4, out5, out6]

Output:
e.g:
BeliefList = [out1[:,beliefs,:,:], out2[:,beliefs,:,:], ....]
AffinityList = [out1[:,Affinities,:,:], out2[:,Affinities,:,:], ....]

Pseudo Algorithm:
Each map will be sliced by nubBelief:numbAffinity ration by axis=1
All upper slices will be concatenated in beliefMap list output
All upper slices will be concatenated in beliefMap list output
"""

'\nInput: \nWill be 6 of this "out" array\ne.g:\n[out1, out2, out3, out4, out5, out6]\n\nOutput:\ne.g:\nBeliefList = [out1[:,beliefs,:,:], out2[:,beliefs,:,:], ....]\nAffinityList = [out1[:,Affinities,:,:], out2[:,Affinities,:,:], ....]\n\nPseudo Algorithm:\nEach map will be sliced by nubBelief:numbAffinity ration by axis=1\nAll upper slices will be concatenated in beliefMap list output\nAll upper slices will be concatenated in beliefMap list output\n'

In [4]:
BeliefList = []
AffinityList = []
for out in InputList:
    BeliefList.append(out[:, :numBeliefMap, :, :])
    AffinityList.append(out[:, numBeliefMap:, :, :])

In [5]:
len(BeliefList)

6

In [6]:
BeliefList[0].shape

(16, 9, 10, 10)

In [7]:
AffinityList[0].shape

(16, 16, 10, 10)

## Functional Implementation

In [8]:
def reshape_maps(InputList):
    """
    :param InputList: varyable list from forward pass of ResPose
    InputList example for 6th stage output without multiclass has length 6 with each element having size
    (numbBatch, 25, W/8, H/8), where W and H are network-input-image dimensions (for dope 400x400)

    Future: Later each list element of the list may have size   (numbBatch, (numbClass x 25), W/8, H/8)
    where numbClass != 1
    When this condition is true the function will behave differently

    :return:
    beliefList: List of Belief maps generated at different stages. Each element will have shape:
    (numbBatch, 9, W/8, H/8). The top 9 maps of each out
    affinityList: List of Affinity maps generated at different stages. Each element will have shape:
    (numbBatch, 16, W/8, H/8). The bottom 16 maps of each out
    """
    beliefList = []
    affinityList = []
    numBeliefMap = 9
    for out in InputList:
        beliefList.append(out[:, :numBeliefMap, :, :])
        affinityList.append(out[:, numBeliefMap:, :, :])
    return beliefList, affinityList

In [9]:
outBeliefList, outAffinityList = reshape_maps(InputList)
print(f"outBeliefList len: {len(outBeliefList)}")
print(f"outAffinityList len: {len(outAffinityList)}")
print(f"outBeliefList[0] shape: {outBeliefList[0].shape}")
print(f"outAffinityList[0] shape: {outAffinityList[0].shape}")

outBeliefList len: 6
outAffinityList len: 6
outBeliefList[0] shape: (16, 9, 10, 10)
outAffinityList[0] shape: (16, 16, 10, 10)


## Demo Distribution Success
Here I demo functioning of the functio in a more intuitive way. Each feature map will be of size 1x1.

In [10]:
import numpy as np
batch = 1
W, H = 1,1
numb_maps = 25
numBeliefMap = 9
numAffinity = 16
out = np.arange(batch * numb_maps * W * H)

print("Before Resizing shape of out:")
print(out.shape)
out = out.reshape(batch, numb_maps, W, H)
print("After Resizing shape of out:")
print(out.shape)

InputList = [out, out, out, out, out, out]



outBeliefList, outAffinityList = reshape_maps(InputList)
print(f"outBeliefList len: {len(outBeliefList)}")
print(f"outAffinityList len: {len(outAffinityList)}")
print(f"outBeliefList[0] shape: {outBeliefList[0].shape}")
print(f"outAffinityList[0] shape: {outAffinityList[0].shape}")

Before Resizing shape of out:
(25,)
After Resizing shape of out:
(1, 25, 1, 1)
outBeliefList len: 6
outAffinityList len: 6
outBeliefList[0] shape: (1, 9, 1, 1)
outAffinityList[0] shape: (1, 16, 1, 1)


As can be seen that first 9 maps are in belief list

In [11]:
outBeliefList[0]

array([[[[0]],

        [[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]],

        [[6]],

        [[7]],

        [[8]]]])

As can be seen that last 16 maps are in affinity list

In [12]:
outAffinityList[0]

array([[[[ 9]],

        [[10]],

        [[11]],

        [[12]],

        [[13]],

        [[14]],

        [[15]],

        [[16]],

        [[17]],

        [[18]],

        [[19]],

        [[20]],

        [[21]],

        [[22]],

        [[23]],

        [[24]]]])